[[setting-up-databases]]
=== Setting up databases
The quickstart is configured to use h2 for demonstration only. For production, you will need to switch to something like postgresql or mysql.

Below there is some help on configuring the database. Additionally, there is some information on reconfiguring wildfly. A better approach is to install a configuration specifically for the desired database using galleon. In that case any information on wildfly configuration can be skipped.

==== postgresql
We'll describe the process for the main calendar engine. The others are very similar.

All bedework and wildfly configuration files are in standalone/configuration/ - we'll just refer to the relative path. 

  * Name: caldb (you can change that if you wish)
  * Configuration: bedework/bwcore/dbconfig.xml
  * datasource: CalendarDS

===== Configure postgresql
You'll probably need to configure postgres to allow your chosen role access to the server and databases.

Depending on how you're running the system you may need to modify postgresql.conf and pg_haba.conf - both located by default in the data directory.

If you're running postgres on a separate system you may need to change the listen_addresses value and port:

[source]
----
listen_addresses = 'localhost'     # what IP address(es) to listen on;
                                   # comma-separated list of addresses;
                                   # defaults to 'localhost'; use '*' for all
                                   # (change requires restart)
port = 5432                        # (change requires restart)            
----

Change "localhost" to "*" or a list of addresses.

5432 is the default port.

To allow your account access you will need to add a line or lines to pg_hba.conf near the end something like:

[source]
----
host    all             bedework        10.0.0.1/32        md5
----
This can be made more restrictive by naming the db.


Create a database with a known id/password. Ensure it is accessible from the host you are running bedework on.

The psql commands are something like:

[source]
----
create role bw with login password 'xxxxxxxxx';
create database caldb owner bw;
----

Some or all of the following seems to be required. Note it also seems to be important to connect to the database first:
----
\c caldb
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO bw;
grant all privileges on database caldb to bw;
----

===== Check configurations
You MUST install the postgres version for this to work. Most of the configuration is already done for you. You will need to provide the id and password.

Configuration overrides are found in
----
<wildfly>/bin/bwcommon.conf
----

For example: replace
----
#JAVA_OPTS="$JAVA_OPTS -Dorg.bedework.site.db.id.calendar=sa
#JAVA_OPTS="$JAVA_OPTS -Dorg.bedework.site.db.pw.calendar=sa
----

with

----
JAVA_OPTS="$JAVA_OPTS -Dorg.bedework.site.db.id.calendar=bw
#JAVA_OPTS="$JAVA_OPTS -Dorg.bedework.site.db.pw.calendar=xxxx
----

Use the psql client application to install the initial schema and data.

[source]
----
psql caldb < <path-to-wildfly>/standalone/data/bedework/postgresql/caldb.sql
----

Note this file sets the owner to 'bw'. If you want a different owner then edit the file first.

===== Do the same for other databases.
If you are running the notifier do the same for that database:

----
psql
create database notifydb owner bw;
grant all privileges on database notifydb to bw;
\q
psql notifydb < /opt/bedework/wildfly/docs/schema/postgresql/notifyschema-pg.sql
----
and update bwcommon.conf.

----
psql
create database synchdb owner bw;
grant all privileges on database synchdb to bw;
\q
psql notifydb < /opt/bedework/wildfly/docs/schema/postgresql/synchschema-pg.sql
----

Similarly for the synch engine:


===== Install opensearch
===== Start wildfly
There will be a number of erros because of the lack of data

In the cli enter the command

[source]
----
./wildfly/bin/bwcli.sh jmxUrl http://localhost:8080/jolokia -id <id> -pw <pw>
restoreCal "/full/path/to/initbedework.xml"
----
The quotes are required. Some activity should ensue.

Reindex the data - again use the cli

[source]
----
rebuildidx
----

wait for it to terminate - then enter

[source]
----
listidx
----
The alias ***bwuser*** should be pointing at the index before the last one just created.

In the cli

[source]
----
makeidxprod index-name
----
replacing ***index-name*** with that last name - no quotes.

==== MySQL

TBD

Set the hibernate dialect in the config file:
[source,xml]
----
    <ormProperty>hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect</ormProperty>
----
