[[elasticsearch]]
=== Elasticsearch
Bedework uses ElasticSearch as the indexer engine. As objects are created destroyed and updated they are indexed through calls to the indexer. The indexer can run as an embedded engine - as it arrives in the quickstart - or as an external service - which will be required for clustering.

Currently elasticSearch is run completely unsecured. DO NOT run in production with the ES interfaces open to the outside.

You can run ES on the same server but preferably it should be running on a different server. ES - depending on the amount of data and types of search - can use a lot of memory for caching of filters. See the ES site for full instructions on running and installing.

In general this is an easy process - ES offers various installation formats of all their versions.

Bedework requires a small number of changes to the configuration. These are available in the quickstart in

[source]
----
bedework/config/bedework/elasticsearch/elasticsearch.yml
----

The changes made are

[source]
----
action.auto_create_index: ".security*,.monitoring*,.watches,.triggered_watches,.watcher-history*,.ml*"*

# Limit to inline only
script.allowed_types: inline
----

Prevent ES from creating indexes implicitly. This can cause issues when reindexing.

[source]
----
cluster.name: bedework-2019
...
node.name: bw2019-1
...
cluster.initial_master_nodes: ["bw2019-1"]
----

Use specific names for the cluster and nodes.
