[[elasticsearch]]
=== Elasticsearch
Bedework uses ElasticSearch as the indexer engine. As objects are created destroyed and updated they are indexed through calls to the indexer. The indexer can run as a local application, useful for development - or as an external service - which will be required for clustering.

It is safer to NOT run in production with the ES interfaces open to the outside. ES now has various configuration options available. Bedework supports basic user authentication. Currently you can run unauthenticated but ES will generate a lot of warnings in the log.

You can run ES on the same server but preferably it should be running on a different server. ES - depending on the amount of data and types of search - can use a lot of memory for caching of filters. See the ES site for full instructions on running and installing.

In general this is an easy process - ES offers various installation formats of all their versions.

Bedework requires a small number of changes to the configuration. These are available in the quickstart in

[source]
----
bedework/config/bedework/elasticsearch/elasticsearch.yml
----

The changes made are

[source]
----
action.auto_create_index: ".security*,.monitoring*,.watches,.triggered_watches,.watcher-history*,.ml*"*

xpack.security.enabled: true

# Limit to inline only
script.allowed_types: inline
----

Prevent ES from creating indexes implicitly. This can cause issues when reindexing.

[source]
----
cluster.name: bedework-2019
...
node.name: bw2019-1
...
cluster.initial_master_nodes: ["bw2019-1"]
----

Use specific names for the cluster and nodes.

[[installing]]
==== Installing ElasticSearch 7.14.0 as a service
There are a number of options available.

Look here for downloadable copies https://www.elastic.co/downloads/past-releases/elasticsearch-7-14-0

Some instructions are here: https://linuxize.com/post/how-to-install-elasticsearch-on-ubuntu-18-04/

If you're looking to install as a production service you need to install elasticsearch as a service. The instructions here are for installing as a service on Ubuntu.

.................
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.14.0-amd64.deb
sudo dpkg -i elasticsearch-7.14.0-amd64.deb
sudo systemctl enable elasticsearch.service
.................

Copy the Ubuntu service configuration out of the bedework quickstart to replace the elasticsearch config.

.................
sudo cp <quickstart>/bedework/config/bedework/elasticsearch/ubuntu-svc-elasticsearch.yml /etc/elasticsearch/elasticsearch.yml
sudo systemctl start elasticsearch.service
.................

After installing and starting the service you will need to restore and reindex the data. For instructions see <<reindex>>.

==== Installing a runnable ElasticSearch 7.14.0
If you just want to try out bedework it may be easier to install elasticsearch as a runnable module.

.................
cd <somewhere>
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.14.0-darwin-x86_64.tar.gz
gunzip elasticsearch-7.14.0-darwin-x86_64.tar.gz
tar xf elasticsearch-7.14.0-darwin-x86_64.tar
cp <path-to>/quickstart-3.13.2/bedework/config/bedework/elasticsearch/elasticsearch.yml elasticsearch-7.14.0/config/
.................

In your <home>/.bw file add

.................
#
# ES options
#
bwESdatadir="<somewhere>/elasticsearch-7.14.0/data/"
.................

Then you can use the restore script to restore the data and indexes:

.................
cd <quickstart>/
./resetQS.sh
.................

