[[featurepack-install]]
=== Install bedework as a wildfly feature
(Not yet released)

==== Note: Security

When installing bedework on wildfly steps must be taken to ensure that services that should be hidden are not exposed on the network.

Do NOT expose the elasticsearch and database ports by - for example - opening up all ports to the network.

The best approach is to disable all ports and only open up those necessary. Bedework only uses the standard web ports. Additionally, even for the web ports (80, 8080 etc) it is best to pass traffic through haproxy or apache web server and only allow known contexts (/cal, /caladmin etc).

==== Galleon, wildfly and bedework
Wildfly can be installed by using the galleon installer, which allows the installation of tailored instances of wildfly.

Additionally extra features can be installed using the same aproach. Bedework now can be installed in this way with a choice of features.

The steps are (described in detail below)

* Install jdk 11

*  <<elasticsearch,Install and configure elastic search>>

* If installing for postgres install the database and create an id/pw for access.

* install wildfly with bedework as a feature

* Start wildfly

* Set a management id/password for the cli

* restart wildfly (so the new id/pw is used)

* For postgres initialise the database

* reindex.

==== Install wildfly and bedework
Bedework is installed as a feature pack which has a dependency on wildfly. The galleon tool supports layers which effectively define a particular flavor of the feature.

Many bedework layers have multiple versions for supported databases. For each the appropriate driver will be installed and datasources will be configured. The database is indicated by the suffix "-xx" where xx is:

.Bedework supported database configurations
|===
| Suffix | Database | Notes

| h2
| h2
| Used for quickstart and demo purposes only

| pg
| postgresql
| Postgresql 9 drivers are installed and datasources are configured.

|===

Following are tables showing all defined layers. Many are flagged as dependencies of others so, for example, bw-calendar-pg will include bw-calendar-ro.

The bw-prod* levels provide a more production ready version which will probably still require configuration changes but should be close.

.Top level layers
|===
| Layer | Function

| bw-demo-xx
| Deploy all bedework components for the indicated database as a demo system.

The system will include apacheds as an ldap server with a preconfigured set of accounts - all with the password "bedework".
|===

Thd next set of layers are used to install specific bedework apps. These could be used to install a specific subset of applications.

.Specific app layers
|===
| Layer | Function

| bw-calendar-ro
| Deploy the readonly calendar system (public events web service and feeder) along with the timezone service. No database drivers or datasources are configured.

| bw-calendar-xx
| Deploy the full calendar system (readonly, admin and submission tools) for the indicated database along with the timezone service.

| bw-carddav-xx
| Deploy the carddav gateway server for the indicated database along with the timezone service.

| bw-eventreg-xx
| Deploy the event registration service for the indicated database

| bw-notify-h2
| Deploy the notification service for the indicated database

| bw-selfreg-h2
| Deploy the self registration service for the indicated database

| bw-synch-xx
| Deploy the full synch engine for the indicated database along with the timezone service.

| bw-tzserver
| Deploy the timezone service
|===

The next layers are used to install certain functions and may be useful with some of the application layers.

.Subsidiary layers
|===
| Layer | Function

| bw-auth-apacheds
| Configure wildfly to handle ldap authentication using a deployed apacheds ldap server. This is used for the demo system and testing.

| bw-auth-ldap
| Configure wildfly to handle ldap authentication. This is the same configuration used for apacheds. It WILL need editing to connect to other ldap servers but should provide a good starting point.

| bw-auth-props
| Authenticate using the wildfly property files. Not used much.
|===

The remainder are dependencies of the other layers..

.Lower level layers
|===
| Layer | Function

| bw-calendar-rw
| Configuration needed by all calendar app levels.

| bw-common
| Configuration needed by all levels.

| postgresql-driver
| Used by other layers that use postgresql

|===

Note that, while different database layers can be mixed, it's not clear what will result from selecting the same application for different databases, e.g. bw-calendar-h2 AND bw-calendar-pg.

