[[featurepack-install]]
=== Install bedework as a wildfly feature
(Not yet released)

==== Note: Security

When installing bedework on wildfly steps must be taken to ensure that services that should be hidden are not exposed on the network.

Do NOT expose the elasticsearch and database ports by - for example - opening up all ports to the network.

The best approach is to disable all ports and only open up those necessary. Bedework only uses the standard web ports. Additionally, even for the web ports (80, 8080 etc) it is best to pass traffic through haproxy or apache web server and only allow known contexts (/cal, /caladmin etc).

==== Galleon, wildfly and bedework
Wildfly can be installed by using the galleon installer, which allows the installation of tailored instances of wildfly.

Additionally extra features can be installed using the same aproach. Bedework now can be installed in this way with a choice of features.

The steps are (described in detail below)

* Install jdk 11

*  <<elasticsearch,Install and configure elastic search>>

* If installing for postgres install the database and create an id/pw for access.

* install wildfly with bedework as a feature

* Start wildfly

* Set the administrator id/password

* restart wildfly (so the new id/pw is used)

* For postgres initialise the database

* reindex.

==== Install wildfly and bedework
Bedework is installed as a feature pack which has a dependency on wildfly. The galleon tool supports layers which effectively define a particular flavor of the feature.

.Bedework supported layers
|===
| Layer | Function

| bw-all-h2
| Deploy all bedework components using the supplied h2 databases. Wildfly datasources will be created for h2.

| bw-all-pg
| Deploy all bedework components for postgresql. Wildfly datasources will be created for postgresql.

| bw-calendar-ro
| Deploy the readonly calendar system (public events web service and feeder) along with the timezone service

| bw-calendar-h2
| Deploy the full calendar system (readonly, admin and submission tools) using the supplied h2 database along with the timezone service. A wildfly datasource will be created for h2.

| bw-calendar-pg
| Deploy the full calendar system (readonly, admin and submission tools) for a postgresql database along with the timezone service. A wildfly datasource will be created for postgresql.

| bw-synch-h2
| Deploy the full synch engine using the supplied h2 database along with the timezone service. A wildfly datasource will be created for h2.

| bw-synch-pg
| Deploy the full synch engine for a postgresql database along with the timezone service. A wildfly datasource will be created for postgresql.

| bw-tzserver
| Deploy the timezone service
|===

Note that the h2 versions are only suitable for demonstration purposes. The postgresql versions should be installed for production.

Also note that, while different database layers can be mixed, it's not clear what will result from selecting the same application for different databases, e.g. bw-calendar-h2 AND bw-calendar-pg.

