[[featurepack-install]]
=== Install bedework as a wildfly feature
Version 4 only.

NOTE: This page is still being updated. The <<install-demo>> steps are
correct (probably) but the detailed steps beyond still require work.

==== Note: Security

When installing bedework on wildfly steps must be taken to ensure that services that should be hidden are not exposed on the network.

Do NOT expose the OpenSearch and database ports by - for example - opening up all ports to the network.

The demo version provides a copy of the minimal opensearch system. This comes with explicit warnings:
----
Please know what you are doing when using this artifact. It contains no security features and is designed to be used only when embedded with another solution or service.

End users are not suggested to use this. Use at your own risk.
----

The best approach is to disable all ports and only open up those necessary. Bedework only uses the ports 8080, 8081 (and 9990 for the wildfly HAL console). Additionally, even for those ports it is best to pass traffic through haproxy or apache web server and only allow known contexts (/cal, /caladmin etc.) and redirect all unknown traffic to "/cal".

==== Galleon, wildfly and bedework
Wildfly can be installed by using the galleon installer, which allows the installation of tailored instances of wildfly.

Additionally extra features can be installed using the same approach. Bedework now can be installed in this way with a choice of features.

[[install-demo]]
==== Fast-track demo version
This will install a version of wildfly with bedework with a full set
of demonstration clients. A demo version of opensearch and apacheds
will also be included.

These steps have been tested on a mac and on the latest LTS linux. Any examples are for Ubuntu.

NOTE: If this fails, and you are going to retry I suggest first
remove the wildfly directory created when running galleon
before retrying.

* Install jdk 17
----
apt install openjdk-17-jdk
----

* In window 1 - Create a directory and cd into it.

* Download galleon
----
wget https://github.com/wildfly/galleon/releases/download/5.2.2.Final/galleon-5.2.2.Final.zip
----
and unzip.

* run galleon to install - this is all one command:
----
./galleon-5.2.2.Final/bin/galleon.sh \
   install org.bedework.deploy:bw-wf-feature-pack:4.1.0
   --dir=wildfly --verbose --layers=bw-demoall-h2,web-console
----

* In window 2 cd into the same directory and start the required services:
----
    export JAVA_HOME=<where the jdk is installed>
    ./wildfly/bin/bwstarth2.sh
    ./wildfly/bin/bwdirstart.sh
    ./wildfly/bin/bwstartoschqs.sh
    tail -f ./wildfly/opensearch/logs/bedework-2019.log
----

 wait till it says something about cluster state going yellow

* Back in the first window
----
./wildfly/bin/bwstartwildfly.sh
----
 and wait for the messages listing the indexes

----
bwcategory20220114t153229<----bwcategory
bwcollection20220114t153228<----bwcollection
bwcontact20220114t153232<----bwcontact
bwevent20220114t153234<----bwevent
bwfilter20220114t153233<----bwfilter
bwlocation20220114t153230<----bwlocation
bwpreferences20220114t153226<----bwpreferences
bwprincipal20220114t153223<----bwprincipal
bwresource20220114t153235<----bwresource
----

* Browse to +
http://localhost:8080/ +
for the starter page

==== More detailed steps:
These are the steps to install a version closer to a production ready
bedework. As noted earlier you should run bedework behind a front-end
service such as haproxy or apache. Wildfly can deliver any associated
static content so there is no need to move that content elsewhere.

* Install jdk 17

* If installing for postgres install the database and create an id/pw for access.

* Download galleon
wget https://github.com/wildfly/galleon/releases/download/5.2.2.Final/galleon-5.2.2.Final.zip
and unzip.
  and unzip.

* Run galleon to deploy wildfly with a bedework service +
You will probably want to change the *--layers* parameter to
select a subset of the bedework installation - see <<wildfly-bedework-layers>>
----
./galleon-5.2.2.Final/bin/galleon.sh \
   install org.bedework.deploy:bw-wf-feature-pack:4.1.0
   --dir=wildfly-26.0.1-Final --verbose --layers=bw-cal-eventsubmit-pg,web-console

ln -s wildfly-26.0.1.Final wildfly
----

* <<opensearch,Install and configure OpenSearch>>

* Start wildfly

* Set a management id/password for the cli

* restart wildfly (so the new id/pw is used)

* For postgres initialise the database

* reindex.

[[wildfly-bedework-layers]]
==== Wildfly and bedework layers
Bedework is installed as a feature pack which has a dependency on wildfly. The galleon tool supports layers which effectively define a particular flavor of the feature.

Many bedework layers have multiple versions for supported databases. For each the appropriate driver will be installed and datasources will be configured. The database is indicated by the suffix "-xx" where xx is:

.Bedework supported database configurations
|===
| Suffix | Database | Notes

| h2
| h2
| Used for quickstart and demo purposes only

| mysql
| mysql (and probably mariadb)
| Mysql 8 drivers are installed and datasources are configured.

| pg
| postgresql
| Postgresql 9 drivers are installed and datasources are configured.

|===

Following are tables showing all defined layers. Many are flagged as dependencies of others so, for example, bw-calendar-pg will include bw-calendar-ro. In general the only layers to use are the top level
layers that specify a database.

The bw-prod* levels provide a more production ready version which will probably still require configuration changes but should be close.

The demo systems will include apacheds as an ldap server with
a preconfigured set of accounts - all with the password
"bedework". Also the minimal version of OpenSearch will be
installed. Startup scripts will be included in the wildfly/bin
directory to start and stop each of the services.

.Top level layers
|===
| Layer | Function

| bw-demoall-xx
| Deploy all bedework components for the indicated database as a demo system.

| bw-demopublic-xx
| Deploy all bedework public events components for the indicated database as a demo system.

| bw-democaluser-xx
| Deploy only bedework personal and group calendaring
components for the indicated database as a demo system.
|===

Thd next set of layers are used to install specific bedework apps. These could be used to install a specific subset of applications.

.Specific app layers
|===
| Layer | Function

| bw-public-ro
| Deploy the readonly public events system (web clients and service and feeder) along with the timezone service. No database drivers or datasources are configured.

| bw-public-xx
| Deploy the full public events system (readonly, admin and submission tools) for the indicated database along with the timezone service.

| bw-caluser-xx
| Deploy the personal and group calendaring system
 for the indicated database along with the timezone service.

| bw-carddav-xx
| Deploy the carddav gateway server for the indicated database along with the timezone service.

| bw-cal-eventsubmit-xx
| Deploy the bw-public-xx layer and the event submission client for the indicated database

| bw-eventreg-xx
| Deploy the event registration service for the indicated database

| bw-notify-h2
| Deploy the notification service for the indicated database

| bw-selfreg-h2
| Deploy the self registration service for the indicated database

| bw-synch-xx
| Deploy the full synch engine for the indicated database along with the timezone service.

| bw-tzserver
| Deploy the timezone service
|===

The next layers are used to install libraries used by servlet filters for CAS authentication or the keycloak servlet filter for saml V2 (shibboleth).

.Servlet filter layers
|===
| Layer | Function

| bw-keycloak-saml-filter
| Adds the keycloak servlet filter libraries. Further configuration to the affected servlets will still be required. See <<keycloak-saml>>

| bw-cas-filter
| Adds the CAS filter libraries. Further configuration to the affected servlets will still be required.
|===

The next layers are used to install certain functions and may be useful with some of the application layers.

.Subsidiary layers
|===
| Layer | Function

| bw-auth-apacheds
| Configure wildfly to handle ldap authentication using a deployed apacheds ldap server. This is used for the demo system and testing.

| bw-auth-ldap
| Configure wildfly to handle ldap authentication. This is the same configuration used for apacheds. It WILL need editing to connect to other ldap servers but should provide a good starting point.

| bw-auth-props
| Authenticate using the wildfly property files. Not used much.
|===

The remainder are dependencies of the other layers..

.Lower level layers
|===
| Layer | Function

| bw-calendar-rw
| Configuration needed by all calendar app levels.

| bw-common
| Configuration needed by all levels.

| bw-h2
| Installs an h2 driver. Used by other layers that use h2 for jdbc.

| bw-postgresql
| Installs a postgresql driver. Used by other layers that use postgresql for jdbc.

|===

Note that, while different database layers can be mixed, it's not clear what will result from selecting the same application for different databases, e.g. bw-public-h2 AND bw-public-pg.

In addition to the bedework layers there are wildfly layers that might be useful.

.Wildfly layers
|===
| Layer | Function

| web-console
| A console which gives access to the wildfly application server. See https://hal.github.io/documentation/manual/

|===

==== Installing examples
These assume galleon has been installed and is runnable. For example it may be installed in the home directory and runnable as:

----
~/galleon-4.2.8.Final/bin/galleon.sh
----

In the following examples we will simply write galleon.sh

.Calendar server with console
=========
galleon.sh install org.bedework:bw-wf-feature-pack:4.0.3 --dir=wildfly --verbose --layers=bw-public-pg,web-console
=========

==== Installing snapshot version
This may not work as snapshots can be out-of-date or inconsistent but for reference...

Download and unzip galleon then run the binary and enter the commands as shown:

[source]
----
./galleon-4.2.8.Final/bin/galleon.sh
maven add-repository --name=ossrh-snapshots --url=https://oss.sonatype.org/content/repositories/snapshots/ --enable-snapshot=true
maven resolve-feature-pack org.bedework.deploy:bw-wf-feature-pack:4.0.4-SNAPSHOT
install org.bedework.deploy:bw-wf-feature-pack:4.0.4-SNAPSHOT --dir=wildfly-26.0.1.Final --verbose --layers=bw-demo-pg,web-console
exit
----
