[[installing-the-quickstart]]
For versions 4.0.0 onwards it is not necessary to install a quickstart. You can install a quickstart if you wish to do development or have convenient access to the sources.

If you are only interested in having a runnable version for demonstration or production then see the instructions at <<featurepack-install>>

=== Installing the quickstart (3.12.x onwards)

The current quickstart is installed by executing a script which will create the quickstart directory and then download, clone and build. In the event of a failure part way through, the script may be restarted with the **restart** parameter.

NOTE: This requires git 2.x or greater. The clones use a tag rather than branch and this does not work for older gits.

The latest script may be downloaded from https://github.com/Bedework/bedework/raw/master/build/quickstart/linux/installQS.sh[github]. Alternatively clone the https://github.com/Bedework/bedework.git[bedework repo] and use the script at *bedework/build/quickstart/linux/installQS.sh*

Specific versions of the script are at:

* https://github.com/Bedework/bedework/raw/bedework-3.13.2/build/quickstart/linux/installQS.sh[3.13.2]
* https://github.com/Bedework/bedework/raw/bedework-3.13.1/build/quickstart/linux/installQS.sh[3.13.1]
* https://github.com/Bedework/bedework/raw/bedework-3.13.0/build/quickstart/linux/installQS.sh[3.13.0]
 * https://github.com/Bedework/bedework/raw/bedework-3.12.7/build/quickstart/linux/installQS.sh[3.12.7]
 * https://github.com/Bedework/bedework/raw/bedework-3.12.6/build/quickstart/linux/installQS.sh[3.12.6]
 * https://github.com/Bedework/bedework/raw/bedework-3.12.5/build/quickstart/linux/installQS.sh[3.12.5]
 * https://github.com/Bedework/bedework/raw/bedework-3.12.3/build/quickstart/linux/installQS.sh[3.12.3]

==== Which version
The script will ask you if you want the latest, developmentor pre-release version.

You probably want latest. The dev version is obviously for development and can be very unstable. The pre-release version is ther only for testing of the install script.

==== Apacheds
The script will install apacheds. This will install a directory with some initial ids in place for testing. Ultimately you'll want to use your own directory service.

==== OpenSearch
You need a running OpenSearch - currently release 1.2.3 The glleon install will provide a script to install a docker image and customize it for the quickstart.

This requires you to have docker and docker-compose installed first.

The instructions related to installing a docker image can be found at https://opensearch.org/docs

After the install is complete use the 2 scripts bwstartosch.sh and bwstoposch.sh to start and stop the docker image.

If you want to install your own copy and configure it the configuration directory is wildfly/standalone/configuration/bedework/opensearch/config. Use this to replace the config in the downloaded OpenSearch.

==== Maven
Maven is required if you want to install the sources. If not you can skip this section.

This is a maven project and as usual you need to set up your maven profile in ~/.m2/settings.xml. The script will display a possible settings.xml file with the paths filled in.

If you want to merge in the profile to an existing settings.xml ensure you also merge in the *pluginGroups* section.

The profile does not need to be active by default if you have other profiles. The build process will specify the bedework-qs profile.

Below is the contents of an example settings.xml file. This file must be set up before allowing the script to continue on to the builds otherwise they will fail during deployment.

[source,xml]
----
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                         http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <pluginGroups>
    <pluginGroup>org.bedework</pluginGroup>
  </pluginGroups>

  <profiles>
    <profile>
      <id>bedework-3</id>
      <activation>
        <activeByDefault>false</activeByDefault>
      </activation>
      <properties>
        <org.bedework.deployment.basedir>$qs</org.bedework.deployment.basedir>
        <org.bedework.deployment.properties>$qs/bedework/config/wildfly.deploy.properties</org.bedework.deployment.properties>
      </properties>
    </profile>
  </profiles>
</settings>

----
[[default-maven-profiles]]
==== Default Maven Profiles
Note there appears to be a bug in the use of ***activeByDefault***.
Explicitly specifying a profile with the maven -P parameter is supposed
to deactivate a profile marked as activeByDefault. This is not (always?)
happening.

If you only have profile marking by default should be fine. To ensure
only one profile (or the expected profiles) are active cd into the project
and try

[source]
----
mvn -P bedework-3 help:active-profiles
----

==== Settings for build and install
The bw and install scripts now source a .bw file in the home directory
which can set some defaults.

To alleviate some of the issues of having multiple maven profiles for bedework
builds set the profile here with the *bw-mvnProfile* property. Note the setting needs to include the -P.

When building with maven the profile provides the location of the deployment properties. For the quickstart this is located in the bedework module at *bedework/config/wildfly.deploy.properties*.

When using the nobuild option you need to take a copy of that file and modify it according to the needs of your installation. Update the *.bw* file property *bw_deployProps* to define the location of the modified property file.

An example .bw file is:
[source]
----
#
# Defaults for bw script
#
echo "Setting defaults from .bw"
bw_mvnProfile="-P bedework_dev"

bw_deployProps="/home/myhome/bwstuff/myprops.properties"

----

==== Security
During the install an id and password will be set up so that the install process can reindex the data. These will allow use of the cli and the hawtio console.

==== Building
In many cases it is possible to simply cd in to the appropriate directory and do a mvn install with the bedework-3 profile. However there is a **bw** script which - while taking longer - does build all projects a module depends upon. This avoids the need to work out the dependency orderings of the independent projects. Thus

[source]
----
./bw bwcal
----

will build a lot of projects eventually building the client project which deploys an ear file.

==== Deploying
As part of the bedework project there is a maven plugin which uses a properties file to handle post-build deployment issues. Essentially the ear or war as built acts as a template for the deployer.

The deployment process may involve inserting filters for CAS, adding property values to web.xml files, cloning entire wars for calendar suites etc.

The file *bedework/config/wildfly.deploy.properties* is the quickstart version of that file.

When developing your own service the first thing to do is create a repository with your files and copy the above file into that repository. Then set the *org.bedework.deployment.properties* value in your maven settings.xml to point to that file.

DO NOT change the *org.bedework.deployment.basedir* property - unless you move the quickstart. This property is used to locate the wildfly instance.
