[[installing-bedwork]]
=== Installing bedework on Ubuntu
. Make sure that apt is up to date
+
.................
sudo apt-get update
.................
. Ensure java 17 jdk installed
+
.................
sudo apt-get install openjdk-17-jdk-headless
sudo update-alternatives --config java
.................
+
The last command should state there are no alternatives but if another has been installed pick the appropriate version.
. Create a directory in which to install.
+
We'll refer to this directory as <bw>
+
----
mkdir <bw>
cd <bw>
----
. Install wildfly with bedework using galleon
+
Follow the instructions at <<featurepack-install>>.

. Install OpenSearch 1.2.3
+
The deployed wildfly has scripts to install a docker image and start and stop it. See <<installing-opensearch>> for instructions on installing and (re)indexing.
You'll need to start the system before reindexing.

. Start the system
+
.................
cd <into quickstart>
./wildfly/bin/bwstarth2.sh
./wildfly/bin/bwdirstart.sh
./wildfly/bin/bwstartwildfly.sh
.................
+
If you need to reindex there will certainly be some errors at startup.
. Reindex
+
Use the cli to run the reindexer
.................
./wildfly/bin/bwcli.sh jmxUrl http://localhost:8080/jolokia -id hawtadmin -pw mypw
help
idx list
idx rebuild
idx list
idx makeprod all
exit
.................
