[[installing-bedwork]]
=== Installing bedework on Ubuntu
. Make sure that apt is up to date
+
.................
sudo apt-get update
.................
. Ensure java 11 jdk installed
+
.................
sudo apt-get install openjdk-11-jdk-headless
sudo update-alternatives --config java
.................
+
The last command should state there are no alternatives but if another has been installed pick the appropriate version.
. Install wildfly with bedework using galleon
+
If you are not wanting to install the quickstart for builds and development then install a wildfly service by following the instructions at <<featurepack-install>>.
and disregard the remaining instructiosn below.
. Install maven if you want to do builds.
+
.................
sudo apt install maven
.................
. Install git if you want to install the quickstart
+
.................
sudo apt install git
.................
. Set up maven
+
If you are doing builds of versions before 4.0.0 then set up the maven profile which must be named "bedework-3"
+
.................
mkdir ~/.m2
emacs ~/.m2/settings.xml
.................
+
and paste in a modified form of the following (change the paths
"/home/mike/bw-3.13.2/" to correspond to the directory you're about
to create)
+
.................
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                         http://maven.apache.org/xsd/settings-1.0.0.xsd">
<pluginGroups>
<pluginGroup>org.bedework</pluginGroup>
</pluginGroups>

  <profiles>
    <profile>
      <id>bedework-3</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <org.bedework.deployment.basedir>/home/mike/bw-3.13.2/quickstart-dev</org.bedework.deployment.basedir>
        <org.bedework.deployment.properties>/home/mike/bw-3.13.2/quickstart-dev/bedework/config/wildfly.deploy.properties</org.bedework.deployment.properties>
      </properties>
    </profile>
  </profiles>
</settings>
.................
. Provide a bw settings file.
+
If necessary create a *.bw* file in your home directory and add properties to it. Currently the only proeprties allow setting the profile for the *.bw* script used to build and the location of the deployment proeprties used to configure your deployed modules.
+
An example file is
+
.................
#
# Defaults for bw script
#
echo "Setting defaults from .bw"
bw_mvnProfile="-P bedework_dev"

bw_deployProps="/home/myhome/bwstuff/myprops.properties"
.................
. Install the quickstart
+
We create a directory in which to install bedework, download an install script and execute the script.
+
.................
mkdir bw-4.0.0
wget https://github.com/Bedework/bedework/raw/bedework-4.0.0/build/quickstart/linux/installQS.sh
chmod +x installQS.sh
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
./installQS.sh
.................
+
and answer the questions presented to you. If you need to restart - probably easier to delete and recreate the directory.
+
Some time will pass. You'll be asked to provide an id and password for wildfly admin. I suggest hawtadmin and a password of your own choosing. More time will pass...

. Install OpenSearch 1.2.3
+
The eployed wildfly has scripts to install a docker image and start and stop it. See <<opensearch>> for instructions on installing and (re)indexing.
You'll need to start the system before reindexing.

. Start the system
+
.................
cd <into quickstart>
./wildfly/bin/bwstarth2.sh
./wildfly/bin/bwdirstart.sh
./wildfly/bin/bwstartwildfly.sh
.................
+
If you need to reindex there will certainly be some errors at startup.
. Reindex
+
Use the installed script to run the reindexer
.................
cd <into quickstart>
./wildfly/bin/bw-cli.sh -id hawtadmin -pw mypw
help
listidx
rebuildidx
listidx
makeidxprod all
q
.................
