[[auth-users]]
=== Public events authorised users
These are users with rights to create events, perhaps publish them and possibly have access to calendar suite setup.

==== Creating a user
Go to the "Users" tab and click on "Manage Admin Roles".

If the user does not appear in the list then type the account into the box labeled "Edit admin roles by userid" and hit enter.

All users should have the "Public Events" flag set.

Users who may create but not publish should have the "Content Admin" flag set.

Users who may create and publish will also have the "Approver" flag set.

==== Updating a user
Go to the same location, "Users" -> "Manage Admin Roles", locate the user in the list and click on the "edit" link.

Flags may be set or unset from there.

==== Adding to groups.
Until the user is added to a group or groups they cannot create events. Each calendar suite will have one or more groups associated with it. Typically there is an admin group associated directly with the suite and a submission group which is a member of the admin group.

Approvers are typically added to the admin group and event creators get added to the submission group.

==== A problem to be resolved later:
Note that the rights of the users are attached to their auth user entry. So a user is always an approver whatever groups they are in.

There is no provision for a user being an approver in one group and an event creator in another. At some point we may move the rights to the associated groups so that approval rights will come about because of group membership.
