=== Subscribing to a feed for public calendars.

You probably want the incoming events to all be flagged with a specific category or categories. This can be useful for filtering.It makes it easier to include the calendar collections imported by the sync engine. Before carrying out the following steps ensure these categories are created.

For public events there are a few more options available when subscribing.

*Process Locations and Contacts:* This causes locations and contacts to be moved into x-properties *"X-BEDEWORK-LOCATION"* and *"X-BEDEWORK-CONTACT"*. The receiving end (bedework) may carry out further actions to validate the location or contact and as a result may set a preexisting location or contact in the event. The x-property is always available for display but this process allows the system to validate the location/contact.

*Process categories:* This does the same for categories.

==== Note:
If you don't select those options then categories and locations will be created in bedework. This is probably not what is wanted as these are uncurated.

By setting the *Process....* flag you ensure that such locations and categories don't end up in the database.

*Suppress deletion of events?* This means that if events disappear from the feed they will stay in the database. This effectively turns the feed into a change feed adn can significantly reduce the size of the data. It does mean that events that MUST be deleted will require help from an administrator with sufficient privileges.
 
==== Creating a public subscription

As a super user

  * Switch to the System tab and select "Manage calendars and folders".
  * Open up "public" and click the "+" on the cals folder.
  * Set the name - e.g "Athletics"
  * Check off categories for filtering
    ** Click on "show/hide categories used for filtering"
    ** Scroll down and select a previously created category or categories
  * Check off any categories you want applied on input -
    ** Click on "show/hide categories for auto-tagging on input"
    ** Scroll down and select a previously created category or categories
  * Mark as a subscription
  * Set the URL in the URl field
  * Set an id/password if necessary
  * Select the "Process Locations and Contacts" and "Process Categories" checkboxes if desired (probably so)
  * Set the location key field name for mapping locations
  * Set the refresh rate in minutes
  * Save

==== Mapping Locations
Locations created and stored within bedework are broken out into a number of fields. Out of these the following are used to create a combined address value which is used for export and import mapping:

  * Street address
  * Room
  * City
  * State
  * zip/postcode

These values are separated by a comma and a space. Missing values are skipped.

The update process matches the value of the supplied LOCATION property against that combined value.

If there is an EXACT match then the bedework location will be attached to the syncronized event. Otherwise the location will be left in the x-property. Feeds and the front end display will normally display the x-location as the location for the event.

==== Mapping categories
An equivalent process takes place with categories though the mapping is much simpler. Categories only have a single value. An exact match in the imported event will cause the bedework category to be applied.

The use of bedework categories is important for much of the front-end filtering of events as this is driven primarily by categories.

As an example if we have the alias structure +
`performances/comedy` +
and comedy is tagged with the category *comedy* and performances with the category *performances* then the imported event needs both categories.

==== Examples


