[[building-bedwork]]
=== Building bedework

Any examples tend to be ubuntu but bedework can be built on any system that supports java17.

. Ensure java 17 jdk is installed
+
.................
sudo apt-get install openjdk-17-jdk-headless
sudo update-alternatives --config java
.................
+
The last command should state there are no alternatives but if another has been installed pick the appropriate version.

. Install maven
.................
sudo apt install maven
.................

. Install git
+
.................
sudo apt install git
.................

. Set up maven
+
If you are doing builds of versions before 4.0.0 then set up the maven profile which must be named "bedework-3"
+
.................
mkdir ~/.m2
emacs ~/.m2/settings.xml
.................
+
and paste in a modified form of the following (change the paths
"/home/mike/bedework/" to correspond to the directory you're about
to create)
+
.................
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                         http://maven.apache.org/xsd/settings-1.0.0.xsd">
<pluginGroups>
<pluginGroup>org.bedework</pluginGroup>
</pluginGroups>

  <profiles>
    <profile>
      <id>bedework-3</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <org.bedework.deployment.basedir>/home/mike/bedework/quickstart-dev</org.bedework.deployment.basedir>
        <org.bedework.deployment.properties>/home/mike/bedework/quickstart-dev/bedework/config/wildfly.deploy.properties</org.bedework.deployment.properties>
      </properties>
    </profile>
  </profiles>
</settings>
.................
. Provide a bw settings file.
+
If necessary create a *.bw* file in your home directory and add properties to it. Currently, the only properties allow setting the profile for the *.bw* script used to build and the location of the deployment proeprties used to configure your deployed modules.
+
An example file is
+
.................
#
# Defaults for bw script
#
echo "Setting defaults from .bw"
bw_mvnProfile="-P bedework_dev"

bw_deployProps="/home/myhome/bwstuff/myprops.properties"
.................

. Create a directory in which to place sources and wildfly.
+
Much of the build assumes a directory in which we have each of the bedework projects and a working wildfly deployment. We'll refer to this directory as <bw>.

. Cd into <bw> and install wildfly
+
Follow the instructions in <<installing-bedwork>>. Choose a version which runs your db of choice and installs a copy of opensearch.
+
If you want to use postgres as your db you need to install that yourself. See <<setting-up-databases>>

. Create wildfly symlink
+
This provides a consistent name for the server.
