[[release-notes]]
=== Release Notes

Specific changes to xsl and javascript can be found at <<xsl-changes>>

==== Dev - To Be Release 4.3.0?:
===== Database schema fixes.
====== Table mapping removed - drop constraints
A table mapping was removed from hibernate and this has resulted in constraint violation exceptions when deleting events.
To fix this drop a couple of foreign key constraints.

for mysql:

----
alter table bw_recurrences drop foreign key `bw_ri_mstr_fk`;

alter table bw_recurrences drop foreign key `bw_ri_ov_fk`;
----

or the equivalent for postgres.

====== Columns missing for rdates and exdates
This is a very long-standing omission. The flag for floating date/times was not stored. Thankfully used very rarely (not at all in any of th epublic events data).

Adding these cleans up the jpa mapping in orm.xml.
----
alter table bw_event_rdates add column r_floating character(1);

alter table bw_event_exdates add column ex_floating character(1);

alter table bw_eventann_rdates add column r_floating character(1);

alter table bw_eventann_exdates add column ex_floating character(1);
----

====== Freebusy component mapping wrong
Again for a long time. The fb component is really an embedded item - not an entity.

We'll move the primary key to eventid, drop the not-null constraints on id and seq (though we could just delete the columns).

----
ALTER TABLE bw_fbcomp DROP CONSTRAINT bw_fbcomp_pkey;
alter table bw_fbcomp alter column bwid drop not null;
alter table bw_fbcomp alter column bwseq drop not null;
ALTER TABLE bw_fbcomp add CONSTRAINT bw_fbcomp_pkey primary key (eventid);
----

===== Upcoming changes

* Cross the jakarta boundary. Will mean upgrading wildfly.
* Work on removing struts - may just upgrade. There seems to be renewed activity on that project.
* Create migration tool to rewrite or modify database to allow new simplified schema and allow removal of hibernate as a dependency.
* Move client side operations into a high level client intended to be usable via web actions or a cli.

==== Release 4.2.0 (2024/12/02):
===== Change summary
====== UI
* More changes to detect and prevent multi-tab use in event add/update
* Many changes to remove dependencies on action form objects.

====== Indexing
* Single event retrieval wasn't excluding tombstoned entities.
* Retrieval of 'special' xprops didn't eliminate tab delimiter when no params were present.
* Updated to OpenSearch version 2.18.0. It appears that the 2.18.0 server will update the 2.1.0 files so a reindex may not be necessary. It also appears that the 2.18.0 bedework will work with a 2.1.0 server.

====== Translation
* Fix handling of UNTIL element in recurrences when converting to/from xml
* Missing checks for absent values
* Add processing for exdate and fix exrule

====== Synch engine
* Add refresh feature to synch engine with new button on the admin screen. Will cause an immediate resynch of the subscription. Useful when fixing bugs in the data or the receiving end.
* Was not updating changes correctly. Added xprops were missed

====== Others
* Made more exceptions unchecked
* When read-only and getting special calendar, return a fake for missing calendar. Caused errors when we were missing the polls calendar for example.
* Various other VPOLL changes including supporting PARTICIPANT as scheduling entities.
* Cannot have a static variable for the session factory in util-hibernate. Opted to remove and let callers manage that. Prevented synch, notify and others working.
* Rebuilt the web test suite and added more tests.
* CalDAV SupportedComponents was not working. Fixed

==== Release 4.1.0 (2024/04/04):
===== Change summary
There are changes that will mean some config or stylesheet
change when upgrading. More details may be seen below.

  * Moved to jdk17.
  * Move submissions root into system properties from event submit config
  * Remove all setting of newColPath from event form.
  * Added flag to mark collection as primary. Must be set on "/public/cals/MainCal"
  * Replaced struts-1 with struts-2. Considered moving from struts altogether, but it's a considerable amount of work. May yet do so.
  * Upgraded to opensearch 2.1.0
  * Upgraded to wildfly 26.1.3.Final
  * Removed the bw-xml module and moved most if the content into existing or new modules. Affects config as wsdls are now on a different path.

==== Some bug fixes
  * Don't fail with an exception if synch server unavailable.
+
The exception was causing calendar modifications to fail if the synch engine was unavailable.

  * Recurrence date was being created incorrectly - missing tzid.
+
Deleting of instances would fail because of a recurrence id mismatch
  * Add calls to close scroll contexts. Waiting for timeout causes problems.
+
Under moderate load we'd run out of scroll contexts. Meant searches would fail with a exception.
  * Fix path in nested queries
+
Prevented filtering on x-property values.
  * Fix restore of BwGeo - stored as BigDecimal value
+
location coordinates were not available.
  * Fix a recurrence instance bug in which invalid recurrenceids would be allowed.
+
Shows up when the url to fetch an instance is edited. Made it appear instances were not being deleted.
  * When deleting set all the timestamps - not just lastmod
  * Fix regexp that collapsed multiple line endings to 1.
  * Move of event wasn't moving overrides
+
When recurring events with overrides were approved we lost all the overrrides.
  * Add information to the view data so that we can sort on the displayed field rather than the path.
+
Items in the left hand navigation were sometimes out of order.
  * If we get hit by multiple requests and 1 gets service unavailable (times out waiting) the session object gets cleared and other requests will fail with no session. Avoid a big trace and just emit a warning.
  * Look out for attempts to update different events on different browser tabs.

===== Significant changes to setting destination calendar collection
Up to now, when adding public events there has been a UI field to set the calendar collection e.g. "/public/cals/MainCal". This has been completely removed. It's unnecessary and caused too many problems.

==== Workflow changes
This has been completely reworked. Making approval of events part
of the update caused problems and in any case the actual process of
approving or publishing events was wrong. Rather than doing a move
the calendar collection path was being updated. It didn't work for
recurring event overrides - probably for a number of releases.

There is now a separate button and action for approval or publishing.

Additionally, it was discovered that moving an event was broken for
overrides. This was fixed.

Much of the flow between pages has been updated.

==== sharethis removed
Sharethis - while offering some possibly useful features - definitely has some privacy issues.
We ran into this because firefox blocks sharethis at high privacy settings.

This article: https://www.privacyinternational.org/case-study/4403/tracking-service-sharethis-be-profiled provides some interesting info.

Additionally, I tried a single event display with sharethis enabled. The results were:

----
18 requests to bedework server - only 2 of which are uncached

12 requests to sharethis - 6 of which are uncached - including a png so what are they hiding in that image?

2 for google analytics

The requests to the bedework server take a total of 700ms. The total load takes 2.23 seconds - most in sharethis.

The google calls take 5ms

sharethis takes twice as long as the actual load of the event. With sharethis the minimum load time is about 1.5sec
----

It probably varies over time but still...

So for performance and privacy purposes I would suggest sites consider removing sharethis. It has been removed from the xsl.

[NOTE]
====
These changes require an update to all calendar collections if you are
upgrading. As a superuser go to System->Manage calendars & folders,
open up the cals folder and select MainCal. Set the "Primary Collection"
checkbox and save.
====


==== Release 4.0.3 (2022/06/03):
This release has been a long time coming largely because it involved a significant amount of restructuring. We've moved away from ElasticSearch because of licence issues, and completely overhauled the deployment process.

Part of the refactoring is to split off the read-only system from the read-write components. This would allow deployment of a much lighter weight service for feeds and web-presence. This work is not yet complete.

The bulk of the rest of the work is to use jboss modules to deploy all code once only and have that available for all services. This reduces memory usage and startup time.

==== ElasticSearch replaced with OpenSearch
This release switches from ElasticSearch to OpenSearch due to the licensing issues with ElasticSearch after version 7.10. This will require a reindex of the data but that would be required anyway as we have made too big a jump between versions for an automatic index update to work.

There's an Amazon perspective on this at https://aws.amazon.com/blogs/opensource/stepping-up-for-a-truly-open-source-elasticsearch/

This has some links to other articles and a search will reveal many others.

While there are reservations about an Amazon supported version it appears to be in their best interests to truly support open source, so - at least for the time being - we have access to a supported Apache 2 licensed search engine.

==== New wildfly galleon feature pack install.
See <<featurepack-install>> for the new way of installing a working system. This is significantly easier than previously.

==== Missing tables in database
*This fix is needed for attachments to work correctly.* It probably does not affect public events as attachments are not (much?) used.
A significant - but long-standing - bug was discovered. Override attachments were not being stored as the table and schema entries were missing. Updating will require adding the table to the database (or recreating the data from the XML dump).

Additionally, ensure the OpenSearch schema is updated
(wildfly/standalone/configuration/bedework/opensearch) and reindex
after the system is updated.

**To fix attachments in postgres.**

 * *BACK UP THE DATABASE*
 * log in to psql
  * select the calendar database and execute the following commands. This may (should) be done ahead of time.

----
CREATE TABLE bw_eventann_attachments (
    eventid integer NOT NULL,
    attachid integer NOT NULL
);

-- Change bedework to whatever you have as owner for your db
ALTER TABLE bw_eventann_attachments OWNER TO bedework;

ALTER TABLE ONLY bw_eventann_attachments
    ADD CONSTRAINT bw_eventann_attachments_pkey PRIMARY KEY (eventid, attachid);

ALTER TABLE ONLY bw_eventann_attachments
    ADD CONSTRAINT bw_eann_attach_fk FOREIGN KEY (attachid) REFERENCES bw_attachments(bwid);

ALTER TABLE ONLY bw_eventann_attachments
    ADD CONSTRAINT bw_eannattach_eid_fk FOREIGN KEY (eventid) REFERENCES bw_event_annotations(eventid);
----

Ensure all configurations are up to date, especially the OpenSearch schema then reindex the data.

===== Changes that might need to be made
If you deploy your own copy of bedework wars and ears there are changes that might affect you. Most of the properties which were changed by the bedework deployment process have been replaced with run-time wildfly properties or by values.

For example, when the xsl war was deployed a property in WEB-INF/jboss-web.xml was replaced.

....
  <context-root>${app.context}</context-root>
....
has been replaced with
....
    <context-root>/approots</context-root>
....

===== Other Bug Fixes

A further significant bug discovered soon after release of 3.13.2:

*Indexing.*
Referenced entities - e.g. locations, were not getting restored
in some cases - see https://github.com/Bedework/bw-calendar-engine/commit/58df20469660d4fe4f2fcef15992147979e3717c#diff-4fb4cfb2524a3a8ea92fc90a4fc31b60

*Further bug with recurrences.* In caldav if an override was deleted from the event it was not deleted from the system.

*Scheduling bug fix* Trying to invite a new bedework user to a meeting could result in an NPE

*Category bug fix* For personal events, multiple new categories in an event were not getting indexed correctly - only the last one. They were created correctly in the database - a reindex will fix any missing categories.

This does not affect public events.

*Core* RDATE only recurring events were not being indexed correctly - instances didn't show up.

*WebClient* Filter out Inbox from result
*WebClient* Events were being moved incorrectly (from Inbox) causing indexing issues.
*WebClient* Fixed the timeview - events near the end of the day appeared in the next days cell.

===== Updates

*Moved most of the deployment into wildfly modules* This is to prepare for splitting
the deployments into read-only web applications (public calendar, etc) from read-write (admin etc).

Note that this has led to a number of changes to the bw script. The
actual web apps rarely need redeploying during development - individual
system modules can be built and deployed on the server.

*New quickstart deployment method.* The quickstart will only be required for development purposes - or for reference to the source. Maven and git are no longer required to install wildfly but are required for the quickstart download.

*Make basic config options constants* A number of path elements - e.g. the name of the user root collection - are in basic system properties - then flagged with "do not change".

These are being changed to constant strings. Changing the internal path element name is likely to be a problem and having to locate the current config in some places is also a problem.

This does not prevent sites setting the display name to something else.

The properties in question are all those that were in basicSystem.xml, which used to populate BasicSystemProperties.

*Updated to wildfly 26.0.1.FINAL* appears to have better memory handling.

*Updated ical4j* brought it close to the Ben Fortuna version.

*JsCalendar* largely supported.

*Timezone server*
  * switch to h2 from leveldb which had too many undesirable dependencies.
  * Move some config out of the zoneinfo directory into the specified data directory. Changed that path to be effectively one level up.
  * Bug fixes for problems encountered when updating the data.

*Refactoring* as part of using wildfly modules.
  * Move Args class from util conf package to util package.

*Many library version updates*

==== Release 3.13.2:
Making a serious effort to get rid of ide warnings. Removing the trivia lets the important stuff stand out. Starting work on implementing new jscalendar and jscontact representations and the jmap protocol.

Changes to log file processor/analyzer. Can produce summary of addresses per ip-address/domain.

    * Bring libraries (jackson + spring) up to the current up to date
    * New jsforj module to parse and generate jscalendar amd jscontact structures.
    * Major internal refactor ready for embedding jsCalendar support:
        ** Moved bw-calendar-engine-ical to bw-calendar-engine-convert
        ** Added packages in that module for ical, jcal and xcal.
    * Cleanup:
        ** Changed a number of internal api calls to use response objects and
           return errorcodes rather than throw exceptions. Where an
           exception is the only way out use RuntimeException.
        ** Where methods rarely throw an exception - or the exception is the result of a truly hosed system - throw runtime exception instead. Cleans up code and we can concentrate on the issues that matter.
    * More fixes to bw script.
    * Performance
        ** Dropped a wait in indexing mark-transaction which was adding a significant amount of time to calls.
        ** Figured out how to handle provisioning a new account when we have a read-only svci. Allowed reinstating read-only for caldav read-only methods.
        ** Reconfigured and rewrote some of the JMS code to allow asynch sends. Required update of a library version.
    * bw-util
        ** move cli libraries into new bw-cliutil project
        ** move bw-util-struts into bw-calendar-client-util
        ** Split into a number of util projects
    * bw-util-logging
        ** Allow setting of log level.
    * webdav
        ** Fixes to report/propfind - allprops and propname were not being handled correctly.
    * Indexing
        ** Use scroll search for multiget query
        ** Delay indexing to end transaction call. Allows for greater efficiency and also less likelihood of index inconsistencies.
        ** Fixed mapping so that queries work better against all_content.
    * Other bugs.
        ** Fixed alarm equality checks. Bad comparisons for some fields.
        ** A few scheduling and sharing fixes.
        ** Add a recurrence instance to db for overrides. Need for link back to master.
        ** Scheduling: fixes for attendees only on override.
        ** Fix cleanup of description and summary strings. Was inserting escaped newlines.

==== Release 3.13.1:
There was a long standing bug in category handling for updates. An attempt
was made to preserve default categories for calsuites when an event is
updated. For example if an event is suggested and accepted the
accepting calsuite has its default category added to the event.

This code was being applied to collections which made it impossible to
turn off a default category added to, e.g. an alias, by mistake.

This release also introduces a new authenticated public context. This
is intended to be used for departmental calendars for example. There were
a number of changes needed to make this work but most of the work will
come in setting up the calendar collections and aliases. Documentation
and examples will follow later as always.

  * Drop the explicit reference to maven profile bedework-3 in the bw script. Fix that script to allow -P <profile> and use that in the install script to use bedework-3 +
  This allows us to specify a default profile that differs from the bedework-3 profile.
  * Additionally - add support for a .bw file in the user home which allows setting of the profile. See <<default-maven-profiles,Default Maven Profiles>>
  * Wildfly galleon installer 4.0.3.Final stopped working soon after the last release. Updating to a later version and hoping this won't break.
  * Updated google maps url generation to use location combinedValues property
  * If the location map url is "NO-LINK" (without quotes) then no link will be generated.
  * Remove BasicHttpClient. This necessitated some config changes -
    ** authCardDav.xml and unauthCardDav.xml in bwengine now have a url rather than host, port and context.
    ** notify/notify-config.xml changed - removed host, port, context. Added URI
  * Web client changes
    ** Change how we select the mode of working -
    ** Config for user and submission clients require new entry - <readWrite>true</readWrite>
    ** Add a new authenticated public client. This should allow limited read-only access to views of the data. Users will be added to admin groups to control the access.
    ** Removed bwapptype parameter from web.xml files. Value is duplicated in client configs.
  * Bug fixes
    ** User TermsFilterBuilder for collections. Was generating partially working query
    ** change "|" to " or " in xsl - was not encoded - broke some pages
    ** Problem related to timestamp handling was causing ES version errors.

==== Release 3.13.0:
This release mostly consists of upgrades to almost the latest ElasticSearch (always a moving target), the currently latest wildfly and to Java 11 the current LTS release.

Installing the quickstart requires that you first install docker if you wish to have a quickstart image of OpenSearch installed.

There have additionally been some minor changes in configuration and the addition of a tool feature to help in calendar suite creation.

Beyond that there is very little functional change since the last release. However, note that the move to the latest ES required a complete rewrite of the query and indexing modules.

  * Upgrade to ES 7.2.0
  * Upgrade to wildfly 17.0.1.Final
    ** Use galleon to install - allows updates
    ** Don't use wildfly modules for deployed ear dependencies.
  * Require java 11.
    ** Many changes to build. Much of the XML support is removed from java core.
    ** Updates to maven plugin versions
  * Minor changes
    ** Add an error log handler
    ** Reduce noise in logs
      *** Remove bogus elements from config files
      *** Remove ldap group member so we don't get annoying error messages
    ** Add auth user update to cli tools
    ** Fix NPE when editing auth user that doesn't exist
    ** Some fixes for travis build

==== Release 3.12.7:
  * Fixes to install script
  * Library updates
    ** Update http version to avoid security issues
    ** Add missing dependencies to eventreg
  * Add tzsvr data to quickstart
  * Changes to tz conversion - still broken
  * XSL fixes - missing approots
  * Client
    ** Remove empty x-properties on event update
  * Log processing
    ** Was missing log prefix in parser
    ** Add more checks for same task
  * Deployment
    ** Use deployment base
  * Sync
    ** Use last-modified if etag not present
  * Watch for null x-properties in event list. Can be caused by deleting them in db.
  *  Indexing
    ** Don't index x-properties - can be large

==== Release 3.12.6:
  * Library updates
    ** Update servlet api version
    ** Update jackson version to avoid security issues
    ** Update http client version to avoid security issues
  * Log analysis
    ** Updates to generated figures and some analysis of access logs
  * Sync process
    ** Update category prop updater to fix NPE
    ** Add callback method to fetch location by combined value. Use it when updating or adding an event.
  * Indexing
    ** Fix location mapping - was missing combined field.
  * Install
    ** bwcli wasn't being built by install script
  * Restores
    ** Restores were failing because the fake event property calpath code was getting an NPE - no principal. Fixed it so principal isn't needed. Caused cascading updates up the stack. Dropped the principal object where possible. Generally only need the href.
    ** Resource content handling was broken in restore. Should just set the byte value and create the blob when we have a session
  * Client
    ** Add action to clear any principals notifications
    ** Fix feeder main/listEvents action - now works
  * Others
    ** Svci pars wasn't handling the readonly flag properly. Worked for unauth but wasn't turning on readonly for authenticated methods.
    ** Drop loader-repository elements from (some) jboss-app.xml
    ** Better error messages when building index docs and in AccessUtil
    ** Watch for null home in CalSuites
    ** Response: Add method to set Response status from a response

==== Release 3.12.5:
  * Logging
    ** Add a bunch of jsonIgnore to the Logged interface to stop the fields turning up in json.
    ** Fix error methods. Use exception message as first param.

  * Client
    ** Cache default filters for ro client. Use calsuite as key
    ** Cache user collections in session. Use calsuite group as key
    ** NoopAction extended MainAction. Should not as it retrieves a lot of unused data.
    ** Make session timeout for /cal and /soedept configurable and default to 5

  * Don't store collection in BwCollectionFilter. Was never used. Just store path as entity
  * Fix FlushMap in utils. Current fetched value was not discarded.
  * Fix bw script - was missing some of the newer modules
  * BwLastMod:
    ** Add JsonIgnore to getDbEntity or we get a loop.
    ** Set the db entity when we clone or we get an NPE

==== Release 3.12.4:
  * Fixed a few bugs.
    ** BwResourceContent bug below
    ** Suppress a request-out log message unlesss really on way out
    ** Index wrapper type for calsuite - not calsuite itself
    ** Try to force refresh after adding calsuite
    ** HttpUtil POST produced Accept rather than Content-type
    ** Bad forward in add calsuite produced bogus error message
  * Updated log analyzer so results are easier to read.
  * Factor deployment modules out of bw-util into new bw-util-deploy

==== Release 3.12.3:
  * Added new cli command to analyze log data.
  * Add new REQUEST-OUT log message for analyzer
  * A number of bug fixes
    ** Touch collection on update of acls - was not getting indexed
    ** Calling wrong indexer to update resource content
    ** Wasn't saving entity in response from indexer
    ** Add cache to SvcSimpleFilterParser so we don't repeatedly attempt to fetch children of collections.
    ** Should be returning an empty array when the event is not found
    ** Was calling wrong method to fetch location for update

Note: A bug was discovered almost immediately. The commit is at https://github.com/Bedework/bw-calendar-engine/commit/c83e77e3f5ceb990029b84ca7440af83fdc4e568 and a patch:

----
Index: bw-calendar-engine-facade/src/main/java/org/bedework/calfacade/BwResourceContent.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- bw-calendar-engine-facade/src/main/java/org/bedework/calfacade/BwResourceContent.java	(revision b248db13b030a73828d7b8c9428dda9ebf262a0c)
+++ bw-calendar-engine-facade/src/main/java/org/bedework/calfacade/BwResourceContent.java	(revision c83e77e3f5ceb990029b84ca7440af83fdc4e568)
@@ -187,14 +187,11 @@
       while((len = str.read(buffer)) != -1) {
         b64out.write(buffer, 0, len);
       }
+      b64out.close();

       return new String(baos.toByteArray());
     } catch (final Throwable t) {
       throw new BedeworkException(t);
-    } finally {
-      try {
-        b64out.close();
-      } catch (Throwable t) {}
     }
   }

----


==== Release 3.12.2:
  * Added new cli command to allow refresh of tz data.
  * Widespread changes to remove references to log4j. All localized in one source file (and a few poms for runnable code).
  * Use asciidoctor to generate this document.

==== Release 3.12.1:
===== Searching for contacts/locations
  * In the admin and event submissions clients replaced simple drop down with a search interface. Requires back end support for the search )a restful style with json response).
  
===== ES only read-only clients.
  * Implement an ES only read-only interface. The public client can be built without any hibernate support as it doesn't interact with the database. This required at least:
    ** Minor API changes
    ** Indexing of more entities - principals, calendar suites, preferences, filters.
    ** New core interface implementation which only handles the read only methods.
    ** Refactored the core to remove a callback. Also to spilt off the read only code.
     
===== Split out ES indexes
  * Significant change to indexing to try to resolve the contacts issue and prepare for upgrade.

  * ES v7 will allow only one type per index. To prepare the index was split into many. Requires a doctype parameter to be added to most calls, significant changes to the (re)indexing process and other associated changes.

  * Almost all calendar engine classes were affected in some way - mostly relatively minor.

  * Configuration changes: no longer have a public/user calendar name. The location of the mappings is a directory - not a file and there are multiple mapping files under directories named with the lowercased doctype name.
  
===== Use ES only read-only interface for CalDAV read-only methods.
  * The hope is this will provide a significant performance improvement for those methods.

===== Other changes.
  * Merged pull request from viqueen. Deal with DAV security issue.

==== Release 3.12.0:
===== Move to github/maven
  * A number of modules have been replaced with their github/maven equivalents from the 4.x branches. Other than changes for the build process these modules are functionally equivalent. This change was initiated to make some module classes available for externally built plugin modules. The 3.x modules and their 4.x replacements are:
    ** rpiutil -> bw-util
    ** bwaccess -> bw-access
    ** webdav -> bw-webdav
    ** caldav -> bw-caldav (bwcaldav is the bedework implementation of the interface)
    ** bwxml -> bw-xml
    ** eventreg -> bw-event-registration
    ** selfreg -> bw-self-registration
    ** synch -> bw-synch
  * Related changes were to build the runnable post-deploy app in bw-util-bw-deploy and run that. Some configuration properties had to be changed to align.
  
  * Having done the above the master on github for the calendar engineand client is now the current 3.x dev version, there is a 4.x branch for future development and release branches will be created as necessary. 
  
===== Related to maven/github switch
  * The urls for wsdls is changed. e.g. /wsdls/synch/wssvc.wsdl becomes /xmlspecs/wsdls/synchws/wssvc.wsdl. This necessitates changes to configurations:
    ** synch/../orgSyncV2.xml
    ** synch/../localBedework.xml
    ** bwengine/synch.xml
    ** bwengine/system.xml
    ** eventreg.xml
  * Yet more refactoring was needed. Turns out we had an unbuildable set of modules with bw-xml depending on bw-util for the deployment. Broke out the 2 modules with a dependency on bw-xml as bw-util2
  * Moved all the xsl into it's own module - bw-calendar-xsl. Thi salso needs changes to configs - all xsl url paths are now prefixed with /approots - the context at which the xsl is deployed. Look for elements appRoots and browserResourceRoots in the configs

===== Scheduling
  * Fixes to scheduling code to try to ensure pending inbox events get deleted
  * Updates to iSchedule client for later version of httplient. Moved some code out of caldav tester into common utils
   
===== Notifications
  * Fix the listeners so they close down without exceptions

===== Websockets
  * Add code to support websockets for a new experimental streaming protocol (a CalConnect initiative)
  * Many changes to build process - wewbsockets applications cannot be inside an ear file. Now possible to deploy as a standalone war. Websockets endpoint is now a separate module.
  * Websockets moduleacts as a proxy to caldav.
  
===== Other 
  * Delay getting a change table entry when realiasing. Was intefering with a test in update.
  * Getting deadlocks when deleting tombstoned events. Change the colpath so they disapppear but need a purge process to finally remove them. 
  * Tasks collections were not getting created with correct type - nor were they returning a supported component type.
  * Some fixes to the selfreg feature and additions to the cli to drive it.
   
==== Release 3.11.2:

===== Indexing
  * Add a reindex operation which reindexes all the data in place. Used when ES schema changes.
  * Add an indexstats operation to get counts for a named index
  * Add a setProdAlias operation. Rebuild index no longer automatically makes new index prod. This also allows us to back off the index.
  * Extra operations added to cli to reindex and change indexes
  * Fix update of UpdateInfo in ES index. Was doing a string concat rather than an increment.
  * Index individual location fields so they can be searched
  * Add a fetch single event method to the indexer
  * Synch around event cache accesses

===== Notifications
  * Add a preference to allow suppression of notifications for a user. This shoudl be applied to public-user to avoid a lot of overhead
  * Change logging is now modified. Messages are now logged to audit.org.bedework.chgnote. Requires a change to standalone.xml or the equivalent
  
===== Sync and orgSync:
  * Add orgSync connector to sync engine
  * Fully index location sub-fields - add a set of keys for mapping locations
  * New indexer methods to enable searching for particular location keys
  * Allow specification of a mapping key in subscription and in x-property
  * Updates x-calendar xsd for mapping key as param
  * Changes to admin client to allow specification of orgSync
  * Upgrade to httpClient to handle orgSync certs
  * Add further parameters to OrgSync subscription -updated admin client to support
  * Unsubscribe before deleting content to avoid race.
  * Get persisted event on fetch for update
  * Allow for pw without id in subscription - it's the key in OrgSync
  * Implement setting category on add and update from containing collection.
  * Update was setting datestamps before checking for no changes - was propagated to db entity preventing further updates.
  * Do a better job of setting content-type and encoding for SOAP interactions.
  * Add array of keys to location entity for use by synch process.
  * Fix handling of locations in Synch engine. Add the locKey parameter to the location. It gets propagated to the x-prop for use later.
  * Refresh rate wasn't getting through. Fixed

===== Public events admin
  * Try to mitigate errors caused when a validation error occurs on publish. Indexed and db version did not match.
  * Added missing retry action in event submit.
  * Fixed race condition when selecting a group in admin client
  * Fix the eventsPending page. POST was losing the filter
  * Calsuite specific approvers
  * Avoid ConcurrentModificationException in admin client
  * Changes for eventreg
      ** Add some commands to cli
      ** Use wildfly modules
      ** More HttpUtil methods for use in eventreg and sync
      ** Fix web.xml and post-deploy for wildfly
  * Use of deleted flag
      ** Index the flag
      ** Changes to allow DeleteEventAction to just set the flag
      ** Searching can filter on deleted flag
      ** Add mark deleted button to form
  * Add tool command to set authuser roles
  * Add tool command to add/remove approver for calsuite

===== Clients
  * Fix errors caused by entry into showEventMore with a new session
  * Switch public client to use href in urls instead of calPath + guid + recurrenceId
  * Last date in header was the same as the first date

===== Other 
  * Removed the principal path elements from the basic config. Changing them is always a bad idea so they may as well be fixed.
  * Use wildfly modules where possible - ensure we get consistent SOAP behavior
  * Further changes for httpclient. Fix to timezones
  * Logging changes to try to reduce output
  * Try to spot ConnectionResetByPeer errors and leave quietly
  * Try to make less noise when a hung session is shut down
  * Avoid tzsvr startup errors - and db should be static
  * Allow setting of session timeout in deploy properties
  * Drop deprecated jboss config
  * Allow setting of soap address in post deploy
  * Try to fix some issues with JMX which surfaced when testing eventreg
  * Add an Events method to calculate instances for recurring event
  * Fix carddav logging
  * Add flag to ifInfo to indicate a dontKill server process. Stops
    autokill killing off some of the long running system jobs.
  * Fixes to get carddav working again. Most of them backported to 3.11.1  
  * Fixes to get vpoll working again. Broke as a result of ical4j upgrade.
  * Add event dumping to the new (incomplete) dump format.
  * Try another approach to stop exceptions when a new user turns up

==== Release 3.11.1:

  * Change the schema and filter to allow searches on x-properties.
  * Backported carddav changes from 3.11.2

  